name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu...
    defaults:
      run:
        shell: bash

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v2.4.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Display Docker Version
        run: docker --version

      - name: List Docker Images
        run: docker images

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker build -t qasimalimirza/python-app-A4:latest .
